Repository azharaiz/duid-django, pull requests merged in 2021-01, with the labels that each got.

#20 [Refactor] Dompet
  .github/workflows/main.yml
  dompet/admin.py
  dompet/models.py
  dompet/serializers.py
  dompet/tests.py
  dompet/util.py
  dompet/views.py
  target/admin.py
  target/models.py
  target/serializers.py
  target/tests.py
  target/urls.py
  target/util.py
  target/views.py
Labels: enhancement

#10 [DOCS] add Database and Package Requirement Documentation
  docs/README.md
  docs/database/README.md
  docs/package_requirement/README.md
Labels: documentation

#9 [CHORES] add category api documentation
  docs/README.md
Labels: documentation

#8 [DOCS] Authentication module
  docs/README.md
Labels: documentation

#14 [FEATURE] Create User
  authentication/serializers.py
  authentication/tests.py
  docs/User.md
  duid/settings.py
  duid/urls.py
  user/__init__.py
  user/apps.py
  user/migrations/__init__.py
  user/tests.py
  user/urls.py
  user/views.py
Labels: documentation, enhancement

#17 [DOCS] add Transaction API documentation
  docs/README.md
Labels: documentation

#21 [FEATURE] Target with investment calculation
  target/models.py
  target/serializers.py
  target/tests.py
  target/util.py
Labels: enhancement

#22 [DOCS] Target API Documentation
  docs/README.md
  target/util.py
Labels: documentation, duplicate

#26 [REFACTOR] refactor transaction test
  transaction/tests/test_base_transaction.py
  transaction/tests/test_transaction_item_view.py
  transaction/tests/test_transaction_model.py
  transaction/tests/test_transaction_view.py
Labels: enhancement
